### ISSUE TITLE
VaultWalletAddress -> addressFormat missing enum elements

### ISSUE THREAD

**Issue by danielkumor** [fireblocks/fireblocks-openapi-spec#33]
```
VaultWalletAddress:
   type: object
   properties:
       ...
         addressFormat:
            type: string
            enum:
               - SEGWIT
               - LEGACY
```

Enum should contains values: 
- BASE
- PAYMENT
- SEGWIT 
- LEGACY
